"""Deterministic synthetic balance-sheet generator and the data boundary.

The generator produces reproducible, balanced portfolios from an integer seed.
Every portfolio it returns is labeled with synthetic provenance recording the
generator version and seed, so any figure can be reproduced exactly.

:func:`ensure_synthetic` is the enforcement point for the ``synthetic_data_only``
policy: code paths that must not accept real data call it to reject anything not
labeled synthetic.
"""

from __future__ import annotations

import random
from datetime import date
from decimal import Decimal

from balancelab.config import Settings, get_settings
from balancelab.domain.base import quantize_money
from balancelab.domain.models import (
    Account,
    AccountCategory,
    DataOrigin,
    Portfolio,
    Provenance,
)
from balancelab.errors import PolicyViolationError

GENERATOR_VERSION = "synthetic-generator@1"

# Illustrative, obviously-synthetic account names. No real institution implied.
_ASSET_NAMES = (
    "Cash and Equivalents",
    "Marketable Securities",
    "Loans Receivable",
    "Property and Equipment",
    "Intangible Assets",
)
_LIABILITY_NAMES = (
    "Customer Deposits",
    "Short-Term Borrowings",
    "Long-Term Debt",
    "Accounts Payable",
    "Other Liabilities",
)


def _random_amount(rng: random.Random, low: int, high: int) -> Decimal:
    """Return a quantized decimal amount in [low, high] with cents."""

    whole = rng.randint(low, high)
    cents = rng.randint(0, 99)
    return quantize_money(Decimal(whole) + (Decimal(cents) / Decimal(100)))


def generate_synthetic_portfolio(
    *,
    seed: int,
    name: str = "Synthetic Demo Bank",
    currency: str = "USD",
    as_of_date: date | None = None,
    n_asset_accounts: int = 3,
    n_liability_accounts: int = 2,
) -> Portfolio:
    """Generate a reproducible, balanced synthetic portfolio.

    The balance-sheet identity holds by construction: a single equity account is
    set to ``total_assets - total_liabilities`` so ``assets == liabilities +
    equity`` exactly. Given the same seed and parameters, the output is
    identical.
    """

    if not (1 <= n_asset_accounts <= len(_ASSET_NAMES)):
        raise ValueError(f"n_asset_accounts must be in 1..{len(_ASSET_NAMES)}")
    if not (1 <= n_liability_accounts <= len(_LIABILITY_NAMES)):
        raise ValueError(f"n_liability_accounts must be in 1..{len(_LIABILITY_NAMES)}")

    # Deterministic PRNG for reproducible synthetic data only; not security-
    # sensitive (seeding is the whole point). Safe to exempt from B311.
    rng = random.Random(seed)  # nosec B311
    as_of = as_of_date or date(2025, 12, 31)

    asset_accounts = tuple(
        Account(
            name=_ASSET_NAMES[i],
            category=AccountCategory.ASSET,
            currency=currency,
            balance=_random_amount(rng, 50_000, 5_000_000),
        )
        for i in range(n_asset_accounts)
    )
    liability_accounts = tuple(
        Account(
            name=_LIABILITY_NAMES[i],
            category=AccountCategory.LIABILITY,
            currency=currency,
            balance=_random_amount(rng, 10_000, 3_000_000),
        )
        for i in range(n_liability_accounts)
    )

    total_assets = sum((a.balance for a in asset_accounts), Decimal(0))
    total_liabilities = sum((a.balance for a in liability_accounts), Decimal(0))
    equity_balance = quantize_money(total_assets - total_liabilities)

    equity_account = Account(
        name="Total Equity",
        category=AccountCategory.EQUITY,
        currency=currency,
        balance=equity_balance,
    )

    provenance = Provenance(
        origin=DataOrigin.SYNTHETIC,
        generator=GENERATOR_VERSION,
        seed=seed,
        license_notes="Synthetic data generated by BalanceLab; no real entity.",
    )

    return Portfolio(
        name=name,
        as_of_date=as_of,
        currency=currency,
        provenance=provenance,
        accounts=(*asset_accounts, *liability_accounts, equity_account),
    )


def ensure_synthetic(portfolio: Portfolio, settings: Settings | None = None) -> Portfolio:
    """Enforce the synthetic-data-only policy.

    Returns the portfolio unchanged when the policy is satisfied. Raises
    :class:`~balancelab.errors.PolicyViolationError` when the policy is in force
    and the portfolio is not labeled synthetic. This is the single boundary the
    rest of the system relies on, so the check lives here rather than being
    re-implemented per call site.
    """

    cfg = settings or get_settings()
    if cfg.synthetic_data_only and not portfolio.provenance.is_synthetic:
        raise PolicyViolationError(
            "synthetic_data_only policy is in force; non-synthetic data rejected",
            details={
                "portfolio_id": portfolio.id,
                "origin": portfolio.provenance.origin.value,
            },
        )
    return portfolio
