#!/usr/bin/env python3
"""Database migration check.

Two levels, so the check is meaningful with or without a live database:

1. **Offline (always):** emit the full upgrade as SQL. This proves every
   migration script imports and compiles against the ORM metadata without
   needing a database.
2. **Online (when a database is configured):** apply migrations to the database
   (`upgrade head`) and then run `alembic check`, which fails if the ORM models
   have drifted from the migrations (i.e. an autogenerated migration is missing).

CI sets ``BALANCELAB_DATABASE_URL`` against a disposable Postgres so the online
path runs there; locally, without a database, the offline smoke still guards
against broken migration scripts.
"""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

from balancelab.config import get_settings

PROJECT_ROOT = Path(__file__).resolve().parent.parent


def _alembic(*args: str) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        [sys.executable, "-m", "alembic", *args],
        cwd=PROJECT_ROOT,
        capture_output=True,
        text=True,
        check=False,
    )


def main() -> int:
    # 1. Offline smoke — always.
    offline = _alembic("upgrade", "head", "--sql")
    if offline.returncode != 0:
        print("offline migration SQL generation failed:", file=sys.stderr)
        print(offline.stderr, file=sys.stderr)
        return 1
    print("migration check: offline SQL generation ok")

    # 2. Online check — only when a database is configured.
    if not get_settings().database_url:
        print("migration check: no database configured — skipping online check (ok)")
        return 0

    upgrade = _alembic("upgrade", "head")
    if upgrade.returncode != 0:
        print("`alembic upgrade head` failed:", file=sys.stderr)
        print(upgrade.stderr, file=sys.stderr)
        return 1

    check = _alembic("check")
    if check.returncode != 0:
        print("`alembic check` failed — models have drifted from migrations:", file=sys.stderr)
        print(check.stdout, file=sys.stderr)
        print(check.stderr, file=sys.stderr)
        return 1

    print("migration check: online upgrade + drift check ok")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
