#!/usr/bin/env python3
"""Database migration check (M0 placeholder).

The shared engineering standard requires a migration-check CI stage. M0 has no
persistence layer yet, so this script asserts that state explicitly and exits
successfully. When migrations are introduced (M1), replace the body with a real
check (e.g. ``alembic upgrade head --sql`` against a disposable database, plus a
"no pending autogenerated changes" assertion).
"""

from __future__ import annotations

import sys
from pathlib import Path

MIGRATIONS_DIR = Path(__file__).resolve().parent.parent / "infra" / "migrations"


def main() -> int:
    if MIGRATIONS_DIR.exists() and any(MIGRATIONS_DIR.iterdir()):
        print(
            "migrations directory is populated but no migration runner is wired; "
            "update scripts/check_migrations.py before merging.",
            file=sys.stderr,
        )
        return 1
    print("migration check: no persistence layer in M0 — nothing to migrate (ok)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
